apiVersion: v1
kind: Service
metadata:
  name: credit-risk-api-service
spec:
  type: NodePort
  selector:
    app: credit-risk-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080